name: Run build and test

"on":
  push:
    branches-ignore:
      - 'next'
      - 'www'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 'latest'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: 6.0

      - name: Setup mongodb-tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.16.1.deb
          sudo apt install ./mongodb-database-tools-*-100.16.1.deb
          mongorestore --version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test